### ISSUE TITLE
PED v. VCF/BCF sanity checking.

### ISSUE THREAD

**Issue by arq5x** [ryanlayer/gqt#22]
Currently, we solely enforce that the _number_ of individuals in the PED and GQT index of the VCF/BCF match.  However, this is still a bit dangerous, since we really want to ensure that all of the sample ids AND the order of the sample Id match.

**Comment by arq5x** [comment]
We need to resolve this near the time that the paper is posted, as currently, GQT strictly assumes two things:

1. That the number of samples in the VCF and the PED are identical.
2. That there order is identical. For example, if Joe is the 5th line in the PED file, the query tool will assume that the correct GQT offset is 4 (0-based). 

It would be safer (better) to have the `convert ped` tool keep a map of sample names in the VCF to their offsets in the GQT index. Then, the SQL queries return sample names as results and hand them off to GQT which uses the associative array to find the correct offsets.  This solves problems 1 and 2.

**Comment by arq5x** [comment]
We need to resolve this near the time that the paper is posted, as currently, GQT strictly assumes two things:

1. That the number of samples in the VCF and the PED are identical.
2. That there order is identical. For example, if Joe is the 5th line in the PED file, the query tool will assume that the correct GQT offset is 4 (0-based). 

It would be safer (better) to have the `convert ped` tool keep a map of sample names in the VCF to their offsets in the GQT index. Then, the SQL queries return sample names as results and hand them off to GQT which uses the associative array to find the correct offsets.  This solves problems 1 and 2.

**Comment by ryanlayer** [comment]
This would require that the supplied file have a field called "Sample Names"

**Comment by arq5x** [comment]
PED has a strict format. The second field is the sample name, no matter what the column is labeled. Regardless, we need a way to not seg fault when indices don't exist and not give erroneous results when samples are in different orders in the PED and VCF.  Otherwise, many unhappy users.

**Comment by ryanlayer** [comment]
Done.
