### ISSUE TITLE
Allow concurrent indexing jobs in the same directory

### ISSUE THREAD

**Issue by ryanlayer** [ryanlayer/gqt#26]
Right now the tmp files are all named the same, and mess each other up.

**Comment by arq5x** [comment]
Use process_id or a hash?

**Comment by ryanlayer** [comment]
I was thinking about prefixing with output gqt file.

On Fri, Apr 17, 2015 at 9:48 AM, Aaron Quinlan <notifications@github.com>
wrote:

> Use process_id or a hash?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ryanlayer/gqt/issues/26#issuecomment-93989476>.
>



-- 
Ryan Layer

**Comment by jeromekelleher** [comment]
+1 on this. It's an unexpected gotcha to have to specify the tmp directory explicitly when performing multiple imports in the same directory. Using [tmpfile](http://linux.die.net/man/3/tmpfile) would probably be the most standard way of doing this.

**Comment by ryanlayer** [comment]
This is actually fixed. I just never closed the issue.
