### ISSUE TITLE
error with example from README

### ISSUE THREAD

**Issue by brentp** [ryanlayer/gqt#28]
```Shell
$ wget --trust-server-names http://bit.ly/gqt_bcf
...
$ bcftools index chr11.11q14.3.bcf 
[bcf_sync] incorrect number of fields (6 != 5) at 50463490:50463490

$ gqt convert bcf -i chr11.11q14.3.bcf
Attempting to autodetect number of variants and samples from chr11.11q14.3.bcf
Could not load CSI index: chr11.11q14.3.bcf
```

**Comment by arq5x** [comment]
@ryanlayer - is the BCF outdated?

**Comment by ryanlayer** [comment]
I cannot recreate this on either OS X or Linux.  What version of bcftools are you using?  Can you hash the bcf you downloaded (md5sum chr11.11q14.3.bcf)?  It should be a36a7bd0e342f146f9c7133da9dc5d9e.

**Comment by arq5x** [comment]
I can't replicate this either. @brentp, seems like a partial download or an old version of bcftools.

**Comment by brentp** [comment]
yeah, old version of bcftools. it's working with latest.

**Comment by abeconnelly** [comment]
This has been resolved but I wanted to give some additional information for anyone having the same issue.  I was using bcftools Version: 0.1.19-96b5f2294a and was getting the same issue.  Installing the latest (check out [the bcftools github page](http://samtools.github.io/bcftools/) for installation instructions) to Version: 1.2-63-g4bfe242 (using htslib 1.2.1-134-g1f45b19) got rid of the error.

**Comment by arq5x** [comment]
@ryanlayer can you add more detail to the dependencies so that explicit versions are noted (e.g., bcftools >= 1.2 and htslib >= 1.2)?
