### ISSUE TITLE
compiling error

### ISSUE THREAD

**Issue by zd1** [ryanlayer/gqt#29]
Dear GQT developers, 

I got the following error while compiling gqt, could you give some advice?

convert.c:122:17: warning: implicit declaration of function 'hts_get_format' is invalid in C99 [-Wimplicit-function-declaration]
            if (hts_get_format(fp)->format==vcf) {
                ^
convert.c:122:37: error: member reference type 'int' is not a pointer
            if (hts_get_format(fp)->format==vcf) {
                ~~~~~~~~~~~~~~~~~~  ^
convert.c:122:45: error: use of undeclared identifier 'vcf'
            if (hts_get_format(fp)->format==vcf) {
                                            ^
convert.c:128:45: error: member reference type 'int' is not a pointer
            } else if ( hts_get_format(fp)->format==bcf ) {
                        ~~~~~~~~~~~~~~~~~~  ^
convert.c:128:53: error: use of undeclared identifier 'bcf'
            } else if ( hts_get_format(fp)->format==bcf ) {
                                                    ^
1 warning and 4 errors generated.

Thanks, 
Zhihao

**Comment by arq5x** [comment]
Hmm, not sure.  What version of GCC?

**Comment by zd1** [comment]
Thanks for very quick reply.  This was on a mac 

Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 6.1.0 (clang-602.0.49) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin14.3.0
Thread model: posix

**Comment by ryanlayer** [comment]
Looks like htslib headers are not found.  Did you download and make htslib then change the path in src/Makefile?

**Comment by zd1** [comment]
Problem solved. Turns out that I was using an old htslib. I just cloned a new copy and it compiled fine. 

Thanks a lot!
