### ISSUE TITLE
Can I use gqt for Imputation data generated by IMPUTE2?

### ISSUE THREAD

**Issue by tushardave26** [ryanlayer/gqt#33]
Hello Folks,

I have imputation data of 1.5TB -- One file per chromosome. I usually asked to search for data of a list of SNPs. Currently, I am using very naive technique i.e. fgrep. But it takes several days to complete the search if I have a long list of SNPs (e.g. 400) (FYI, I am doing a search using 64GB RAM). I am just curious that can I use gqt software for imputation data? If so, how can I accomplish it? I meant is there any tutorial available for that?

Thanks for your help.

Best,
Tushar

**Comment by ryanlayer** [comment]
Can you tell me a little more about what exactly you are doing?

On Tue, Feb 16, 2016 at 2:01 PM, Tushar Harishbhai Dave <
notifications@github.com> wrote:

> Hello Folks,
>
> I have imputation data of 1.5TB -- One file per chromosome. I usually
> asked to search for data of a list of SNPs. Currently, I am using very
> naive technique i.e. fgrep. But it takes several days to complete the
> search if I have a long list of SNPs (e.g. 400) (FYI, I am doing a search
> using 64GB RAM). I am just curious that can I use gqt software for
> imputation data? If so, how can I accomplish it? I meant is there any
> tutorial available for that?
>
> Thanks for your help.
>
> Best,
> Tushar
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ryanlayer/gqt/issues/33>.
>



-- 
Ryan Layer

**Comment by tushardave26** [comment]
@ryanlayer, I apologize about my fragile explanation. 

Here is the detail explanation about my question:

I have GWAS imputed data files that are generated by IMPUTE2 (https://mathgen.stats.ox.ac.uk/impute/impute_v2.html) software. To speed up the imputation process, the process has been divided per chromosome -- meaning 1 job per chromosome. As a result, IMPUTE2 generates one set of result files (i.e. .gen and .sample, Both the files are text files where each column is delimited by space) per chromosome. If you have 22 chromosomes, IMPUTE2 will generate 22 sets of files. The result file look like as follows:

---> .gen file
1 rs1234 1234 A C 1 0 1 2 0 0 0.99 0 0
1 rs2343 2343 G A 0 1 0 1 1 0 0 2 0
................
................

where 1st col = chromosome number
           2nd col = SNP name
           3rd col = position
           4th and 5th col = Allele1 and Allele2 respectively
           6th, 7th and 8th cols = doage data for subject-1
           9th, 10th and 11th cols = dosae data for subject-2
           and so on...

Each row contains information about one SNP. I have 27million rows in a file and have 22 files in.gz format. The number columns vary from 2345 - 15784. 

Now, I usually get the request from our collaborators to search the data for their interest of SNPs. Let say, they are interested in 20 SNPs across the genome. Currently, I am simply searching for each SNP into their respective chromosome files "zfgrep" command with SNP name (i.e. RSID). As the files are so huge and the command has to scan entire file for the search, the entire operation takes a lot of time to finish. 

I am wondering that is it possible to use your tool to address my issue? I meant can I use your tool to index my datasets and use those indexes to query.

I hope this time I am clear enough.

Thanks for your help.

**Comment by jaredo** [comment]
You probably want to convert your .gen files to .bcf using bcftools:

http://samtools.github.io/bcftools/bcftools.html#convert

From .bcf you could convert to .gqt. Although for the type of query you specify, querying the bcf directly may be preferable.

**Comment by tushardave26** [comment]
@jaredo -- thanks for your suggestion. I will look into this.

**Comment by tushardave26** [comment]
I am trying to install GQT on my LINUX (RHEL6) system, but facing an issue. I just followed the instructions for GQT installation (that dictated in README file). I am able to install htslib and sqlite successfully. I also changed the HTS_ROOT and SQLITE_ROOT variable values with correct ones. But when I invoke make command in gqt directory I am facing below error:

cd src; make
make[1]: Entering directory `/local/projects-t2/SIGN/packages/gqt/src'
flex -oparse_q.yy.c parse_q.l
gcc -c -O2 -D_FILE_OFFSET_BITS=64 -Werror -Wuninitialized -o ../obj/timer.o timer.c \
                -I/local/projects-t2/SIGN/packages/htslib -I/local/projects-t2/SIGN/packages/sqlite-amalgamation-3080701
gcc -c -O2 -D_FILE_OFFSET_BITS=64 -Werror -Wuninitialized -o ../obj/misc.o misc.c \
                -I/local/projects-t2/SIGN/packages/htslib -I/local/projects-t2/SIGN/packages/sqlite-amalgamation-3080701
In file included from misc.c:9:
wahbm.h:5:23: error: immintrin.h: No such file or directory
make[1]: *** [../obj/misc.o] Error 1
make[1]: Leaving directory `/local/projects-t2/SIGN/packages/gqt/src'
make: *** [all] Error 2

Please help me to resolve this issue.

Thanks.

**Comment by ryanlayer** [comment]
Which version of gcc are you using?

**Comment by tushardave26** [comment]
Kernel Version:

uname -r

2.6.18-371.1.2.el5

GCC version:

gcc -v

Using built-in specs.
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-libgcj-multifile --enable-languages=c,c++,objc,obj-c++,java,fortran,ada --enable-java-awt=gtk --disable-dssi --disable-plugin --with-java-home=/usr/lib/jvm/java-1.4.2-gcj-1.4.2.0/jre --with-cpu=generic --host=x86_64-redhat-linux
Thread model: posix
gcc version 4.1.2 20080704 (Red Hat 4.1.2-54)

I mentioned that my system has RHEL 6 but from GCC -v output it seems that I have RHEL 4.

I hope this helps.

**Comment by ryanlayer** [comment]
Okay, I think I fixed it.  Please pull the latest and try again.

On Wed, Feb 24, 2016 at 7:34 AM, Tushar Harishbhai Dave <
notifications@github.com> wrote:

> Kernel Version:
>
> uname -r
>
> 2.6.18-371.1.2.el5
>
> GCC version:
>
> gcc -v
>
> Using built-in specs.
> Target: x86_64-redhat-linux
> Configured with: ../configure --prefix=/usr --mandir=/usr/share/man
> --infodir=/usr/share/info --enable-shared --enable-threads=posix
> --enable-checking=release --with-system-zlib --enable-__cxa_atexit
> --disable-libunwind-exceptions --enable-libgcj-multifile
> --enable-languages=c,c++,objc,obj-c++,java,fortran,ada
> --enable-java-awt=gtk --disable-dssi --disable-plugin
> --with-java-home=/usr/lib/jvm/java-1.4.2-gcj-1.4.2.0/jre --with-cpu=generic
> --host=x86_64-redhat-linux
> Thread model: posix
> gcc version 4.1.2 20080704 (Red Hat 4.1.2-54)
>
> I mentioned that my system has RHEL 6 but from GCC -v output it seems that
> I have RHEL 4.
>
> I hope this helps.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ryanlayer/gqt/issues/33#issuecomment-188279853>.
>



-- 
Ryan Layer

**Comment by tushardave26** [comment]
Thanks Ryan for your quick help. I will give it a try and keep you posted.

**Comment by tushardave26** [comment]
Hello Ryan,

I have cloned repository again and try to run make command. Unfortunately, I got the same erorr. FYI the error is pasted below:

cd src; make
make[1]: Entering directory `/local/projects-t2/SIGN/packages/gqt/src'
flex -oparse_q.yy.c parse_q.l
gcc -c -O2 -D_FILE_OFFSET_BITS=64 -Werror -Wuninitialized -o ../obj/timer.o timer.c \
                -I/local/projects-t2/SIGN/packages/htslib -I/local/projects-t2/SIGN/packages/sqlite-amalgamation-3080701
gcc -c -O2 -D_FILE_OFFSET_BITS=64 -Werror -Wuninitialized -o ../obj/misc.o misc.c \
                -I/local/projects-t2/SIGN/packages/htslib -I/local/projects-t2/SIGN/packages/sqlite-amalgamation-3080701
gcc -c -O2 -D_FILE_OFFSET_BITS=64 -Werror -Wuninitialized -o ../obj/query.o query.c \
                -I/local/projects-t2/SIGN/packages/htslib -I/local/projects-t2/SIGN/packages/sqlite-amalgamation-3080701
gcc -c -O2 -D_FILE_OFFSET_BITS=64 -Werror -Wuninitialized -o ../obj/pop.o pop.c \
                -I/local/projects-t2/SIGN/packages/htslib -I/local/projects-t2/SIGN/packages/sqlite-amalgamation-3080701
pop.c:2:23: error: immintrin.h: No such file or directory
make[1]: *** [../obj/pop.o] Error 1
make[1]: Leaving directory `/local/projects-t2/SIGN/packages/gqt/src'
make: *** [all] Error 2

**Comment by ryanlayer** [comment]
Some now pop.c slipped through the cracks.  Please pull and try again.

On Wed, Feb 24, 2016 at 12:08 PM, Tushar Harishbhai Dave <
notifications@github.com> wrote:

> Hello Ryan,
>
> I have cloned repository again and try to run make command. Unfortunately,
> I got the same erorr. FYI the error is pasted below:
>
> cd src; make
> make[1]: Entering directory /local/projects-t2/SIGN/packages/gqt/src'
> flex -oparse_q.yy.c parse_q.l
> gcc -c -O2 -D_FILE_OFFSET_BITS=64 -Werror -Wuninitialized -o
> ../obj/timer.o timer.c \
> -I/local/projects-t2/SIGN/packages/htslib
> -I/local/projects-t2/SIGN/packages/sqlite-amalgamation-3080701
> gcc -c -O2 -D_FILE_OFFSET_BITS=64 -Werror -Wuninitialized -o ../obj/misc.o
> misc.c \
> -I/local/projects-t2/SIGN/packages/htslib
> -I/local/projects-t2/SIGN/packages/sqlite-amalgamation-3080701
> gcc -c -O2 -D_FILE_OFFSET_BITS=64 -Werror -Wuninitialized -o
> ../obj/query.o query.c \
> -I/local/projects-t2/SIGN/packages/htslib
> -I/local/projects-t2/SIGN/packages/sqlite-amalgamation-3080701
> gcc -c -O2 -D_FILE_OFFSET_BITS=64 -Werror -Wuninitialized -o ../obj/pop.o
> pop.c \
> -I/local/projects-t2/SIGN/packages/htslib
> -I/local/projects-t2/SIGN/packages/sqlite-amalgamation-3080701
> pop.c:2:23: error: immintrin.h: No such file or directory
> make[1]: *** [../obj/pop.o] Error 1
> make[1]: Leaving directory/local/projects-t2/SIGN/packages/gqt/src'
> make: *** [all] Error 2
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ryanlayer/gqt/issues/33#issuecomment-188409042>.
>



-- 
Ryan Layer

**Comment by tushardave26** [comment]
Hello Ryan,

Now, I am able to install GQT successfully. Thanks for your all help.

Best,
Tushar
