### ISSUE TITLE
perhaps a typo in functional_tests.sh

### ISSUE THREAD

**Issue by hillan141** [ryanlayer/gqt#34]
Thanks for providing this tool.  Upon installing today, functional_tests.sh failed on RHEL5 with error:

SUCCESS(555): GQT count matches BCFTOOLS count
./functional_tests.sh: line 565: BCFTOOLS: command not found
tail: cannot open `../data/A_vs_B.weir.fst' for reading: No such file or directory
ERROR(603): GQT Fst does not match VCFTOOLS fst
cat: ../data/A_vs_B.weir.fst: No such file or directory

On line 565, replacing 'BCFTOOLS' with '$BCFTOOLS' resolved issue in my environment.

**Comment by ryanlayer** [comment]
Fixed. Thanks for reporting and fixing this.
