### ISSUE TITLE
Possible typo in functional_tests.sh script

### ISSUE THREAD

**Issue by tushardave26** [ryanlayer/gqt#35]
Hello Authors,

At line 573 of script functional_tests.sh under gqt/test/func, the script should have $BCFTOOLS. But the script has BCFTOOLS which cause and error.

Also in the same script at several places, it has bcftool instead of $BCFTOOLS. Can some one explain that why the script has both BCFTOOLS variable and bcftools (the command that invokes the bcftools utility)?

I hope all these make sense.

Thanks.

Best,
Tushar

**Comment by ryanlayer** [comment]
Everything should now be $BCFTOOLS.  Thanks.
